# 不用root_data
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002  --client_lr=0.02 --model=lanet --name=[SIGNCDP-sigma=0.1] --cdp=True --sigma=0.1

# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002  --client_lr=0.02 --model=lanet --name=[SIGNCDP-sigma=0.1] --cdp=True --sigma=0.1 --attack=True --attack_type=label --attack_num=6 --labelflip_attack_frequency=1

# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002  --client_lr=0.02 --model=lanet --name=[SIGNCDP-sigma=0.1] --cdp=True --sigma=0.1 --attack=True --attack_type=pixel --attack_num=6 --pixel_attack_frequency=1

# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002  --client_lr=0.02 --model=lanet --name=[SIGNCDP-sigma=0.1] --cdp=True --sigma=0.1 --attack=True --attack_type=weightflip --attack_num=6 --weightflip_attack_frequency=1

# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002  --client_lr=0.02 --model=lanet --name=[SIGNCDP-sigma=0.1] --cdp=True --sigma=0.1 --attack=True --attack_type=replace --attack_num=1 --attack_replace_round=150


# 使用root_data
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002  --client_lr=0.02 --model=lanet --name=[SIGNCDP-sigma=0.1] --cdp=True --sigma=0.1 --onud_root_data=True

# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002  --client_lr=0.02 --model=lanet --name=[SIGNCDP-sigma=0.1] --cdp=True --sigma=0.1 --attack=True --attack_type=label --attack_num=6 --labelflip_attack_frequency=1 --onud_root_data=True

# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002  --client_lr=0.02 --model=lanet --name=[SIGNCDP-sigma=0.1] --cdp=True --sigma=0.1 --attack=True --attack_type=pixel --attack_num=6 --pixel_attack_frequency=1 --onud_root_data=True

# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002  --client_lr=0.02 --model=lanet --name=[SIGNCDP-sigma=0.1] --cdp=True --sigma=0.1 --attack=True --attack_type=weightflip --attack_num=6 --weightflip_attack_frequency=1 --onud_root_data=True

# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002  --client_lr=0.02 --model=lanet --name=[SIGNCDP-sigma=0.1] --cdp=True --sigma=0.1 --attack=True --attack_type=replace --attack_num=1 --attack_replace_round=150 --onud_root_data=True


# # 使用findAttacker
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_findAttacker_normal] --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_findAttacker_replace] --attack=True --attack_type=replace --attack_num=2 --attack_replace_round=150 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_findAttacker_pixel] --attack=True --attack_type=pixel --attack_num=6 --pixel_attack_frequency=1 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_findAttacker_label] --attack=True --attack_type=label --attack_num=6 --labelflip_attack_frequency=1 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_findAttacker_weight] --attack=True --attack_type=weightflip --attack_num=6 --weightflip_attack_frequency=1 --use_find=True

# # 不使用findAttacker
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_findAttacker_normal] 
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_findAttacker_replace] --attack=True --attack_type=replace --attack_num=6 --attack_replace_round=150
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_findAttacker_pixel] --attack=True --attack_type=pixel --attack_num=6 --pixel_attack_frequency=1
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_findAttacker_label] --attack=True --attack_type=label --attack_num=6 --labelflip_attack_frequency=1
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_findAttacker_weight] --attack=True --attack_type=weightflip --attack_num=6 --weightflip_attack_frequency=1


# 使用Kmeans
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_Kmeans_normal] --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_Kmeans_replace] --attack=True --attack_type=replace --attack_num=2 --attack_replace_round=150 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_Kmeans_pixel] --attack=True --attack_type=pixel --attack_num=6 --pixel_attack_frequency=1 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_Kmeans_label] --attack=True --attack_type=label --attack_num=6 --labelflip_attack_frequency=1 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_Kmeans_weight] --attack=True --attack_type=weightflip --attack_num=6 --weightflip_attack_frequency=1 --use_find=True

# # 使用Kmeans 8/2
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_Kmeans82_normal] --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_Kmeans82_replace] --attack=True --attack_type=replace --attack_num=2 --attack_replace_round=150 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_Kmeans82_pixel] --attack=True --attack_type=pixel --attack_num=6 --pixel_attack_frequency=1 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_Kmeans82_label] --attack=True --attack_type=label --attack_num=6 --labelflip_attack_frequency=1 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_Kmeans82_weight] --attack=True --attack_type=weightflip --attack_num=6 --weightflip_attack_frequency=1 --use_find=True

# 使用CFDP attacker_num=6
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_normal] --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_replace_6_1] --attack=True --attack_type=replace --attack_num=6 --attack_replace_round=150 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_pixel_6_1] --attack=True --attack_type=pixel --attack_num=6 --pixel_attack_frequency=1 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_label_6_1] --attack=True --attack_type=label --attack_num=6 --labelflip_attack_frequency=1 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_weight_6_1] --attack=True --attack_type=weightflip --attack_num=6 --weightflip_attack_frequency=1 --use_find=True
# # #attacknum =4
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_replace_4] --attack=True --attack_type=replace --attack_num=4 --attack_replace_round=150 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_pixel_4] --attack=True --attack_type=pixel --attack_num=4 --pixel_attack_frequency=1 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_label_4] --attack=True --attack_type=label --attack_num=4 --labelflip_attack_frequency=1 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_weight_4] --attack=True --attack_type=weightflip --attack_num=4 --weightflip_attack_frequency=1 --use_find=True
# #attacknum =2
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_replace_2] --attack=True --attack_type=replace --attack_num=2 --attack_replace_round=150 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_pixel_2] --attack=True --attack_type=pixel --attack_num=2 --pixel_attack_frequency=1 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_label_2] --attack=True --attack_type=label --attack_num=2 --labelflip_attack_frequency=1 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_weight_2] --attack=True --attack_type=weightflip --attack_num=2 --weightflip_attack_frequency=1 --use_find=True
# #attacknum =10
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_replace_10] --attack=True --attack_type=replace --attack_num=10 --attack_replace_round=150 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_pixel_10] --attack=True --attack_type=pixel --attack_num=10 --pixel_attack_frequency=1 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_label_10] --attack=True --attack_type=label --attack_num=10 --labelflip_attack_frequency=1 --use_find=True
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_weight_10] --attack=True --attack_type=weightflip --attack_num=10 --weightflip_attack_frequency=1 --use_find=True
# #attacknum =12
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_pixel_16_1] --attack=True --attack_type=pixel --attack_num=16 --pixel_attack_frequency=1 --use_find=True --cfdp_rho=0.65
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_replace_16_1] --attack=True --attack_type=replace --attack_num=16 --attack_replace_round=150 --use_find=True --cfdp_rho=0.65
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_label_16_1] --attack=True --attack_type=label --attack_num=16 --labelflip_attack_frequency=1 --use_find=True --cfdp_rho=0.65
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_weight_16_1] --attack=True --attack_type=weightflip --attack_num=16 --weightflip_attack_frequency=1 --use_find=True --cfdp_rho=0.65


# # 只使用cos进行计算
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP01_replace_10_1] --attack=True --attack_type=replace --attack_num=10 --attack_replace_round=150 --use_find=True --cfdp_rho=0.25 --cfdp_alpha=1 --cfdp_beta=0
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP01_pixel_10_1] --attack=True --attack_type=pixel --attack_num=10 --pixel_attack_frequency=1 --use_find=True --cfdp_rho=0.25 --cfdp_alpha=1 --cfdp_beta=0
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP01_label_10_1] --attack=True --attack_type=label --attack_num=10 --labelflip_attack_frequency=1 --use_find=True --cfdp_rho=0.25 --cfdp_alpha=1 --cfdp_beta=0
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP01_weight_10_1] --attack=True --attack_type=weightflip --attack_num=10 --weightflip_attack_frequency=1 --use_find=True --cfdp_rho=0.25 --cfdp_alpha=1 --cfdp_beta=0

# # 只使用NMI计算
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP10_replace_10_1] --attack=True --attack_type=replace --attack_num=10 --attack_replace_round=150 --use_find=True --cfdp_rho=0.25 --cfdp_alpha=1 --cfdp_beta=0
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP10_pixel_10_1] --attack=True --attack_type=pixel --attack_num=10 --pixel_attack_frequency=1 --use_find=True --cfdp_rho=0.25 --cfdp_alpha=1 --cfdp_beta=0
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP10_label_10_1] --attack=True --attack_type=label --attack_num=10 --labelflip_attack_frequency=1 --use_find=True --cfdp_rho=0.25 --cfdp_alpha=1 --cfdp_beta=0
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP10_weight_10_1] --attack=True --attack_type=weightflip --attack_num=10 --weightflip_attack_frequency=1 --use_find=True --cfdp_rho=0.25 --cfdp_alpha=1 --cfdp_beta=0

# 不是用放缩实验
python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_replace_6_noscale_1] --attack=True --attack_type=replace --attack_num=6 --attack_replace_round=150 --use_find=True --cfdp_rho=0.08
python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_pixel_6_1_noscale_1] --attack=True --attack_type=pixel --attack_num=6 --pixel_attack_frequency=1 --use_find=True --cfdp_rho=0.08
python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_label_6_noscale_1] --attack=True --attack_type=label --attack_num=6 --labelflip_attack_frequency=1 --use_find=True --cfdp_rho=0.08
python FedL.py --round=200 --client_ep=15 --data_distributed=iid --update_type=dirction --onud=True --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[ex_CFDP73_weight_6_noscale_1] --attack=True --attack_type=weightflip --attack_num=6 --weightflip_attack_frequency=1 --use_find=True --cfdp_rho=0.08

# # FedAVG
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[FedAVG_normal] 
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[FedAVG_replace] --attack=True --attack_type=replace --attack_num=6 --attack__iureplace_round=150
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[FedAVG_pixel] --attack=True --attack_type=pixel --attack_num=6 --pixel_attack_frequency=1
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[FedAVG_label] --attack=True --attack_type=label --attack_num=6 --labelflip_attack_frequency=1
# python FedL.py --round=200 --client_ep=15 --data_distributed=iid --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=lanet --name=[FedAVG_weight] --attack=True --attack_type=weightflip --attack_num=6 --weightflip_attack_frequency=1

python FedL.py --num_client=20 --round=300 --client_ep=15 --data_distributed=iid --dataset=cifar10 --client_bs=512 --onud_server_alpha=0.0002 --client_lr=0.02 --model=alexnet --name=[test_ia]