# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_test_DPRSA_F_iid 

# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_labelflip_noniid_2 --attack=True --attack_type=label --attack_num=2
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_labelflip_noniid_4 --attack=True --attack_type=label --attack_num=4
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_labelflip_noniid_6 --attack=True --attack_type=label --attack_num=6
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_labelflip_noniid_8 --attack=True --attack_type=label --attack_num=8
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_labelflip_noniid_10 --attack=True --attack_type=label --attack_num=10
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_labelflip_noniid_12 --attack=True --attack_type=label --attack_num=12
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_labelflip_noniid_14 --attack=True --attack_type=label --attack_num=14
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_labelflip_noniid_16 --attack=True --attack_type=label --attack_num=16
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_labelflip_noniid_18 --attack=True --attack_type=label --attack_num=18

# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_gaussian_noniid_2 --attack=True --attack_type=gaussian --attack_num=2
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_gaussian_noniid_4 --attack=True --attack_type=gaussian --attack_num=4
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_gaussian_noniid_6 --attack=True --attack_type=gaussian --attack_num=6
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_gaussian_noniid_8 --attack=True --attack_type=gaussian --attack_num=8
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_gaussian_noniid_10 --attack=True --attack_type=gaussian --attack_num=10
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_gaussian_noniid_12 --attack=True --attack_type=gaussian --attack_num=12
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_gaussian_noniid_14 --attack=True --attack_type=gaussian --attack_num=14 
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_gaussian_noniid_16 --attack=True --attack_type=gaussian --attack_num=16
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_gaussian_noniid_18 --attack=True --attack_type=gaussian --attack_num=18

# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_pixel_noniid_2 --attack=True --attack_type=pixel --attack_num=2 
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_pixel_noniid_4 --attack=True --attack_type=pixel --attack_num=4 
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_pixel_noniid_6 --attack=True --attack_type=pixel --attack_num=6
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_pixel_noniid_8 --attack=True --attack_type=pixel --attack_num=8
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_pixel_noniid_10 --attack=True --attack_type=pixel --attack_num=10
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_pixel_noniid_12 --attack=True --attack_type=pixel --attack_num=12
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_pixel_noniid_14 --attack=True --attack_type=pixel --attack_num=14
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_pixel_noniid_16 --attack=True --attack_type=pixel --attack_num=16
# python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_pixel_noniid_18 --attack=True --attack_type=pixel --attack_num=18

python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_replace_noniid_2 --attack=True --attack_type=replace --attack_num=2 --attack_replace_round=800
python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_replace_noniid_4 --attack=True --attack_type=replace --attack_num=4 --attack_replace_round=800
python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_replace_noniid_6 --attack=True --attack_type=replace --attack_num=6 --attack_replace_round=800
python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_replace_noniid_8 --attack=True --attack_type=replace --attack_num=8 --attack_replace_round=800
python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_replace_noniid_10 --attack=True --attack_type=replace --attack_num=10 --attack_replace_round=800
python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_replace_noniid_12 --attack=True --attack_type=replace --attack_num=12 --attack_replace_round=800
python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_replace_noniid_14 --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=800
python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_replace_noniid_16 --attack=True --attack_type=replace --attack_num=16 --attack_replace_round=800
python FL_robust.py --round=1000 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --rsa=True --dprsa=True --dprsa_type=F --name=R_DPRSA_F_replace_noniid_18 --attack=True --attack_type=replace --attack_num=18 --attack_replace_round=800