python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_labelflip_mask2_iid_2 --attack=True --attack_type=label --attack_num=2 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_labelflip_mask2_iid_4 --attack=True --attack_type=label --attack_num=4 --robust_agg=True --robust_agg_type=mipc 
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_labelflip_mask2_iid_6 --attack=True --attack_type=label --attack_num=6 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_labelflip_mask2_iid_8 --attack=True --attack_type=label --attack_num=8 --robust_agg=True --robust_agg_type=mipc 
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_labelflip_mask2_iid_10 --attack=True --attack_type=label --attack_num=10 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_labelflip_mask2_iid_12 --attack=True --attack_type=label --attack_num=12 --robust_agg=True --robust_agg_type=mipc 
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_labelflip_mask2_iid_14 --attack=True --attack_type=label --attack_num=14 --robust_agg=True --robust_agg_type=mipc 
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_labelflip_mask2_iid_16 --attack=True --attack_type=label --attack_num=16 --robust_agg=True --robust_agg_type=mipc 
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_labelflip_mask2_iid_18 --attack=True --attack_type=label --attack_num=18 --robust_agg=True --robust_agg_type=mipc

python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_gaussian_mask2_iid_2 --attack=True --attack_type=gaussian --attack_num=2 --robust_agg=True --robust_agg_type=mipc 
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_gaussian_mask2_iid_4 --attack=True --attack_type=gaussian --attack_num=4 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_gaussian_mask2_iid_6 --attack=True --attack_type=gaussian --attack_num=6 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_gaussian_mask2_iid_8 --attack=True --attack_type=gaussian --attack_num=8 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_gaussian_mask2_iid_10 --attack=True --attack_type=gaussian --attack_num=10 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_gaussian_mask2_iid_12 --attack=True --attack_type=gaussian --attack_num=12 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_gaussian_mask2_iid_14 --attack=True --attack_type=gaussian --attack_num=14 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_gaussian_mask2_iid_16 --attack=True --attack_type=gaussian --attack_num=16 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_gaussian_mask2_iid_18 --attack=True --attack_type=gaussian --attack_num=18 --robust_agg=True --robust_agg_type=mipc

python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_replace_mask2_iid_2 --attack=True --attack_type=replace --attack_num=2 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc 
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_replace_mask2_iid_4 --attack=True --attack_type=replace --attack_num=4 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc 
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_replace_mask2_iid_6 --attack=True --attack_type=replace --attack_num=6 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc 
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_replace_mask2_iid_8 --attack=True --attack_type=replace --attack_num=8 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc 
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_replace_mask2_iid_10 --attack=True --attack_type=replace --attack_num=10 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc 
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_replace_mask2_iid_12 --attack=True --attack_type=replace --attack_num=12 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc 
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_replace_mask2_iid_14 --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc 
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_replace_mask2_iid_16 --attack=True --attack_type=replace --attack_num=16 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc 
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_replace_mask2_iid_18 --attack=True --attack_type=replace --attack_num=18 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc 

python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_pixel_mask2_iid_2 --attack=True --attack_type=pixel --attack_num=2 --robust_agg=True --robust_agg_type=mipc 
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_pixel_mask2_iid_4 --attack=True --attack_type=pixel --attack_num=4 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_pixel_mask2_iid_6 --attack=True --attack_type=pixel --attack_num=6 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_pixel_mask2_iid_8 --attack=True --attack_type=pixel --attack_num=8 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_pixel_mask2_iid_10 --attack=True --attack_type=pixel --attack_num=10 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_pixel_mask2_iid_12 --attack=True --attack_type=pixel --attack_num=12 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_pixel_mask2_iid_14 --attack=True --attack_type=pixel --attack_num=14 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_pixel_mask2_iid_16 --attack=True --attack_type=pixel --attack_num=16 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0005 --name=R_mipc_pixel_mask2_iid_18 --attack=True --attack_type=pixel --attack_num=18 --robust_agg=True --robust_agg_type=mipc

