# # FedSIGN 70%
# ## label 70
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=RA_NON_FedSIGN_label_70_NonIID_CIFAR10 --attack=True --attack_type=label --attack_num=14
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=RA_AD_FedSIGN_label_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=mipc --attack=True --attack_type=label --attack_num=14
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=RA_KRUM_FedSIGN_label_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=krum --attack=True --attack_type=label --attack_num=14
# ## gaussian 70
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=RA_NON_FedSIGN_gaussian_70_NonIID_CIFAR10 --attack=True --attack_type=gaussian --attack_num=14
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=RA_AD_FedSIGN_gaussian_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=mipc --attack=True --attack_type=gaussian --attack_num=14
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=RA_KRUM_FedSIGN_gaussian_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=krum --attack=True --attack_type=gaussian --attack_num=14
# ## pixel 70
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=RA_NON_FedSIGN_pixel_70_NonIID_CIFAR10 --attack=True --attack_type=pixel --attack_num=14
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=RA_AD_FedSIGN_pixel_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=mipc --attack=True --attack_type=pixel --attack_num=14
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=RA_KRUM_FedSIGN_pixel_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=krum --attack=True --attack_type=pixel --attack_num=14
# ## replace 70
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=RA_NON_FedSIGN_replace_70_NonIID_CIFAR10 --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=200
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=RA_AD_FedSIGN_replace_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=mipc --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=200
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=RA_KRUM_FedSIGN_replace_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=krum --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=200

# # DPRSA
# ## label 70
# python FL_robust.py --round=500 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --rsa=True --dprsa=True --dprsa_type=F --name=RA_Non_DPRSA_F_label_70_NonIID_CIFAR10 --attack=True --attack_type=label --attack_num=14
# python FL_robust.py --round=500 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --rsa=True --dprsa=True --dprsa_type=F --name=RA_AD_DPRSA_F_label_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=mipc --attack=True --attack_type=label --attack_num=14
# python FL_robust.py --round=500 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --rsa=True --dprsa=True --dprsa_type=F --name=RA_KRUM_DPRSA_F_label_70_NonIID_CIFAR10 --robust_agg_type=krum --attack=True --attack_type=label --attack_num=14
# ## gaussian 70
# python FL_robust.py --round=500 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --rsa=True --dprsa=True --dprsa_type=F --name=RA_Non_DPRSA_F_gaussian_70_NonIID_CIFAR10 --attack=True --attack_type=gaussian --attack_num=14
# python FL_robust.py --round=500 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --rsa=True --dprsa=True --dprsa_type=F --name=RA_AD_DPRSA_F_gaussian_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=mipc --attack=True --attack_type=gaussian --attack_num=14
# python FL_robust.py --round=500 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --rsa=True --dprsa=True --dprsa_type=F --name=RA_KRUM_DPRSA_F_gaussian_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=krum --attack=True --attack_type=gaussian --attack_num=14
# ## pixel 70
# python FL_robust.py --round=500 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --rsa=True --dprsa=True --dprsa_type=F --name=RA_Non_DPRSA_F_pixel_70_NonIID_CIFAR10 --attack=True --attack_type=pixel --attack_num=14
# python FL_robust.py --round=500 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --rsa=True --dprsa=True --dprsa_type=F --name=RA_AD_DPRSA_F_pixel_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=mipc --attack=True --attack_type=pixel --attack_num=14
# python FL_robust.py --round=500 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --rsa=True --dprsa=True --dprsa_type=F --name=RA_KRUM_DPRSA_F_pixel_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=krum --attack=True --attack_type=pixel --attack_num=14
# ## replace 70
# python FL_robust.py --round=500 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --rsa=True --dprsa=True --dprsa_type=F --name=RA_Non_DPRSA_F_replace_70_NonIID_CIFAR10 --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=300
python FL_robust.py --round=500 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --rsa=True --dprsa=True --dprsa_type=F --name=RA_AD_DPRSA_F_replace_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=mipc --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=300
python FL_robust.py --round=500 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --rsa=True --dprsa=True --dprsa_type=F --name=RA_KRUM_DPRSA_F_replace_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=krum --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=300


# Majority Vote
## label 70
python FL_robust.py --round=1000 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --majority_vote=True --name=RA_NON_MajorityVote_label_70_NonIID_CIFAR10 --attack=True --attack_type=label --attack_num=14
python FL_robust.py --round=1000 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --majority_vote=True --name=RA_AD_MajorityVote_label_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=mipc --attack=True --attack_type=label --attack_num=14
python FL_robust.py --round=1000 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --majority_vote=True --name=RA_Krum_MajorityVote_label_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=krum --attack=True --attack_type=label --attack_num=14
## gaussian 70
python FL_robust.py --round=1000 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --majority_vote=True --name=RA_NON_MajorityVote_gaussian_70_NonIID_CIFAR10 --attack=True --attack_type=gaussian --attack_num=14
python FL_robust.py --round=1000 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --majority_vote=True --name=RA_AD_MajorityVote_gaussian_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=mipc --attack=True --attack_type=gaussian --attack_num=14
python FL_robust.py --round=1000 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --majority_vote=True --name=RA_Krum_MajorityVote_gaussian_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=krum --attack=True --attack_type=gaussian --attack_num=14
## pixel 70
python FL_robust.py --round=1000 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --majority_vote=True --name=RA_NON_MajorityVote_pixel_70_NonIID_CIFAR10 --attack=True --attack_type=pixel --attack_num=14
python FL_robust.py --round=1000 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --majority_vote=True --name=RA_AD_MajorityVote_pixel_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=mipc --attack=True --attack_type=pixel --attack_num=14
python FL_robust.py --round=1000 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --majority_vote=True --name=RA_Krum_MajorityVote_pixel_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=krum --attack=True --attack_type=pixel --attack_num=14
## replace 70
python FL_robust.py --round=1000 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --majority_vote=True --name=RA_NON_MajorityVote_replace_70_NonIID_CIFAR10 --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=800
python FL_robust.py --round=1000 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --majority_vote=True --name=RA_AD_MajorityVote_replace_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=mipc --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=800
python FL_robust.py --round=1000 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --majority_vote=True --name=RA_Krum_MajorityVote_replace_70_NonIID_CIFAR10 --robust_agg=True --robust_agg_type=krum --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=800