# python FL-privacy.py --white_box=True --round=301 --client_ep=5 --data_distributed=iid --dataset=cifar10 --client_bs=2048 --client_lr=0.001 --num_client=4 --train_num=4 --update_type=weight --name=P_FedAvg_LDP_5 --ldp=True --ldp_epsilon=5 --ldp_delta=0.00001
# python FL-privacy.py --white_box=True --round=301 --client_ep=5 --data_distributed=iid --dataset=cifar10 --client_bs=2048 --client_lr=0.001 --num_client=4 --train_num=4 --update_type=weight --name=P_FedAvg_LDP_10 --ldp=True --ldp_epsilon=10 --ldp_delta=0.00001
# python FL-privacy.py --white_box=True --round=301 --client_ep=5 --data_distributed=iid --dataset=cifar10 --client_bs=2048 --client_lr=0.001 --num_client=4 --train_num=4 --update_type=weight --name=P_FedAvg_LDP_15 --ldp=True --ldp_epsilon=15 --ldp_delta=0.00001

# python FL-privacy.py --white_box=True --round=300 --client_ep=5 --data_distributed=iid --dataset=cifar10 --client_bs=2048 --client_lr=0.01 --num_client=4 --train_num=4 --update_type=weight --model=alexnet --name=P_FedAvg_LDP_20 --ldp=True --ldp_epsilon=20 --ldp_delta=0.00001 --ldp_clip=3
# python FL-privacy.py --white_box=True --round=300 --client_ep=5 --data_distributed=iid --dataset=cifar10 --client_bs=2048 --client_lr=0.01 --num_client=4 --train_num=4 --update_type=weight --model=alexnet --name=P_FedAvg_LDP_15 --ldp=True --ldp_epsilon=15 --ldp_delta=0.00001 --ldp_clip=3
# python FL-privacy.py --white_box=True --round=300 --client_ep=5 --data_distributed=iid --dataset=cifar10 --client_bs=2048 --client_lr=0.01 --num_client=4 --train_num=4 --update_type=weight --model=alexnet --name=P_FedAvg_LDP_10 --ldp=True --ldp_epsilon=10 --ldp_delta=0.00001 --ldp_clip=3
# python FL-privacy.py --white_box=True --round=300 --client_ep=5 --data_distributed=iid --dataset=cifar10 --client_bs=2048 --client_lr=0.01 --num_client=4 --train_num=4 --update_type=weight --model=alexnet --name=P_FedAvg_LDP_5 --ldp=True --ldp_epsilon=5 --ldp_delta=0.00001 --ldp_clip=3

# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedAvg_LDP_10 --ldp=True --ldp_epsilon=10 --ldp_delta=0.00001 --ldp_clip=3 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedAvg_LDP_20 --ldp=True --ldp_epsilon=20 --ldp_delta=0.00001 --ldp_clip=3 --white_box=True

python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=weight --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedAvg_LDP_MNIST_10 --ldp=True --ldp_epsilon=10 --ldp_delta=0.00001 --ldp_clip=3 --white_box=True
python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=weight --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedAvg_LDP_MNIST_20 --ldp=True --ldp_epsilon=20 --ldp_delta=0.00001 --ldp_clip=3 --white_box=True
python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedAvg_LDP_FMNIST_10 --ldp=True --ldp_epsilon=10 --ldp_delta=0.00001 --ldp_clip=3 --white_box=True
python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedAvg_LDP_FMNIST_20 --ldp=True --ldp_epsilon=20 --ldp_delta=0.00001 --ldp_clip=3 --white_box=True