# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_iid 

# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_labelflip_iid_2 --attack=True --attack_type=label --attack_num=2
# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_labelflip_iid_4 --attack=True --attack_type=label --attack_num=4
# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_labelflip_iid_6 --attack=True --attack_type=label --attack_num=6
# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_labelflip_iid_8 --attack=True --attack_type=label --attack_num=8
# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_labelflip_iid_10 --attack=True --attack_type=label --attack_num=10
# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_labelflip_iid_12 --attack=True --attack_type=label --attack_num=12
# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_labelflip_iid_14 --attack=True --attack_type=label --attack_num=14
# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_labelflip_iid_16 --attack=True --attack_type=label --attack_num=16
# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_labelflip_iid_18 --attack=True --attack_type=label --attack_num=18

python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_gaussian_iid_2 --attack=True --attack_type=gaussian --attack_num=2
python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_gaussian_iid_4 --attack=True --attack_type=gaussian --attack_num=4
python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_gaussian_iid_6 --attack=True --attack_type=gaussian --attack_num=6
python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_gaussian_iid_8 --attack=True --attack_type=gaussian --attack_num=8
python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_gaussian_iid_10 --attack=True --attack_type=gaussian --attack_num=10
python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_gaussian_iid_12 --attack=True --attack_type=gaussian --attack_num=12
python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_gaussian_iid_14 --attack=True --attack_type=gaussian --attack_num=14
python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_gaussian_iid_16 --attack=True --attack_type=gaussian --attack_num=16
python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_gaussian_iid_18 --attack=True --attack_type=gaussian --attack_num=18

python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_replace_iid_2 --attack=True --attack_type=replace --attack_num=2 --attack_replace_round=3500
python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_replace_iid_4 --attack=True --attack_type=replace --attack_num=4 --attack_replace_round=3500
python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_replace_iid_6 --attack=True --attack_type=replace --attack_num=6 --attack_replace_round=3500
python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_replace_iid_8 --attack=True --attack_type=replace --attack_num=8 --attack_replace_round=3500
python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_replace_iid_10 --attack=True --attack_type=replace --attack_num=10 --attack_replace_round=3500
python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_replace_iid_12 --attack=True --attack_type=replace --attack_num=12 --attack_replace_round=3500
python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_replace_iid_14 --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=3500
python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_replace_iid_16 --attack=True --attack_type=replace --attack_num=16 --attack_replace_round=3500
python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_replace_iid_18 --attack=True --attack_type=replace --attack_num=18 --attack_replace_round=3500

# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_pixel_iid_2 --attack=True --attack_type=pixel --attack_num=2 
# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_pixel_iid_4 --attack=True --attack_type=pixel --attack_num=4
# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_pixel_iid_6 --attack=True --attack_type=pixel --attack_num=6
# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_pixel_iid_8 --attack=True --attack_type=pixel --attack_num=8
# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_pixel_iid_10 --attack=True --attack_type=pixel --attack_num=10
# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_pixel_iid_12 --attack=True --attack_type=pixel --attack_num=12
# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_pixel_iid_14 --attack=True --attack_type=pixel --attack_num=14
# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_pixel_iid_16 --attack=True --attack_type=pixel --attack_num=16
# python FL_robust.py --round=4000 --data_distributed=iid --client_ep=5 --update_type=direction --dataset=mnist --client_bs=1024 --model=lanet --majority_vote=True --name=R_MNIST_MajorityVote_pixel_iid_18 --attack=True --attack_type=pixel --attack_num=18