# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_labelflip_mask_v2_noniid_2 --attack=True --attack_type=label --attack_num=2 --robust_agg=True --robust_agg_type=mipc 
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_labelflip_mask_v2_noniid_4 --attack=True --attack_type=label --attack_num=4 --robust_agg=True --robust_agg_type=mipc 
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_labelflip_mask_v2_noniid_6 --attack=True --attack_type=label --attack_num=6 --robust_agg=True --robust_agg_type=mipc 
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_labelflip_mask_v2_noniid_8 --attack=True --attack_type=label --attack_num=8 --robust_agg=True --robust_agg_type=mipc 
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_labelflip_mask_v2_noniid_10 --attack=True --attack_type=label --attack_num=10 --robust_agg=True --robust_agg_type=mipc 
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_labelflip_mask_v2_noniid_12 --attack=True --attack_type=label --attack_num=12 --robust_agg=True --robust_agg_type=mipc
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_labelflip_mask_v2_noniid_14 --attack=True --attack_type=label --attack_num=14 --robust_agg=True --robust_agg_type=mipc 
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_labelflip_mask_v2_noniid_16 --attack=True --attack_type=label --attack_num=16 --robust_agg=True --robust_agg_type=mipc 
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_labelflip_mask_v2_noniid_18 --attack=True --attack_type=label --attack_num=18 --robust_agg=True --robust_agg_type=mipc

# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_gaussian_mask_v2_noniid_2 --attack=True --attack_type=gaussian --attack_num=2 --robust_agg=True --robust_agg_type=mipc 
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_gaussian_mask_v2_noniid_4 --attack=True --attack_type=gaussian --attack_num=4 --robust_agg=True --robust_agg_type=mipc
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_gaussian_mask_v2_noniid_6 --attack=True --attack_type=gaussian --attack_num=6 --robust_agg=True --robust_agg_type=mipc
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_gaussian_mask_v2_noniid_8 --attack=True --attack_type=gaussian --attack_num=8 --robust_agg=True --robust_agg_type=mipc
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_gaussian_mask_v2_noniid_10 --attack=True --attack_type=gaussian --attack_num=10 --robust_agg=True --robust_agg_type=mipc
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_gaussian_mask_v2_noniid_12 --attack=True --attack_type=gaussian --attack_num=12 --robust_agg=True --robust_agg_type=mipc
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_gaussian_mask_v2_noniid_14 --attack=True --attack_type=gaussian --attack_num=14 --robust_agg=True --robust_agg_type=mipc
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_gaussian_mask_v2_noniid_16 --attack=True --attack_type=gaussian --attack_num=16 --robust_agg=True --robust_agg_type=mipc
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_gaussian_mask_v2_noniid_18 --attack=True --attack_type=gaussian --attack_num=18 --robust_agg=True --robust_agg_type=mipc

# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_replace_mask_v2_noniid_2 --attack=True --attack_type=replace --attack_num=2 --attack_replace_round=250 --robust_agg=True --robust_agg_type=mipc 
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_replace_mask_v2_noniid_4 --attack=True --attack_type=replace --attack_num=4 --attack_replace_round=250 --robust_agg=True --robust_agg_type=mipc
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_replace_mask_v2_noniid_6 --attack=True --attack_type=replace --attack_num=6 --attack_replace_round=250 --robust_agg=True --robust_agg_type=mipc
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_replace_mask_v2_noniid_8 --attack=True --attack_type=replace --attack_num=8 --attack_replace_round=250 --robust_agg=True --robust_agg_type=mipc
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_replace_mask_v2_noniid_10 --attack=True --attack_type=replace --attack_num=10 --attack_replace_round=250 --robust_agg=True --robust_agg_type=mipc
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_replace_mask_v2_noniid_12 --attack=True --attack_type=replace --attack_num=12 --attack_replace_round=250 --robust_agg=True --robust_agg_type=mipc
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_replace_mask_v2_noniid_14 --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=250 --robust_agg=True --robust_agg_type=mipc
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_replace_mask_v2_noniid_16 --attack=True --attack_type=replace --attack_num=16 --attack_replace_round=250 --robust_agg=True --robust_agg_type=mipc
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_replace_mask_v2_noniid_18 --attack=True --attack_type=replace --attack_num=18 --attack_replace_round=250 --robust_agg=True --robust_agg_type=mipc

# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_pixel_mask_v2_noniid_2 --attack=True --attack_type=pixel --attack_num=2 --robust_agg=True --robust_agg_type=mipc 
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_pixel_mask_v2_noniid_4 --attack=True --attack_type=pixel --attack_num=4 --robust_agg=True --robust_agg_type=mipc 
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_pixel_mask_v2_noniid_6 --attack=True --attack_type=pixel --attack_num=6 --robust_agg=True --robust_agg_type=mipc 
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_pixel_mask_v2_noniid_8 --attack=True --attack_type=pixel --attack_num=8 --robust_agg=True --robust_agg_type=mipc 
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_pixel_mask_v2_noniid_10 --attack=True --attack_type=pixel --attack_num=10 --robust_agg=True --robust_agg_type=mipc 
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_pixel_mask_v2_noniid_12 --attack=True --attack_type=pixel --attack_num=12 --robust_agg=True --robust_agg_type=mipc 
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_pixel_mask_v2_noniid_14 --attack=True --attack_type=pixel --attack_num=14 --robust_agg=True --robust_agg_type=mipc 
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_pixel_mask_v2_noniid_16 --attack=True --attack_type=pixel --attack_num=16 --robust_agg=True --robust_agg_type=mipc 
# python FL_robust.py --round=300 --client_ep=2 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=alexnet --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.00001 --name=R_mipc_pixel_mask_v2_noniid_18 --attack=True --attack_type=pixel --attack_num=18 --robust_agg=True --robust_agg_type=mipc 
