# #------------------------- FMNIST-------------------------------
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_iid

# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_labelflip_iid_2 --attack=True --attack_type=label --attack_num=2 
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_labelflip_iid_4 --attack=True --attack_type=label --attack_num=4
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_labelflip_iid_6 --attack=True --attack_type=label --attack_num=6
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_labelflip_iid_8 --attack=True --attack_type=label --attack_num=8
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_labelflip_iid_10 --attack=True --attack_type=label --attack_num=10
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_labelflip_iid_12 --attack=True --attack_type=label --attack_num=12
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_labelflip_iid_14 --attack=True --attack_type=label --attack_num=14
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_labelflip_iid_16 --attack=True --attack_type=label --attack_num=16
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_labelflip_iid_18 --attack=True --attack_type=label --attack_num=18

# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_gaussian_iid_2 --attack=True --attack_type=gaussian --attack_num=2 
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_gaussian_iid_4 --attack=True --attack_type=gaussian --attack_num=4
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_gaussian_iid_6 --attack=True --attack_type=gaussian --attack_num=6
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_gaussian_iid_8 --attack=True --attack_type=gaussian --attack_num=8
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_gaussian_iid_10 --attack=True --attack_type=gaussian --attack_num=10
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_gaussian_iid_12 --attack=True --attack_type=gaussian --attack_num=12
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_gaussian_iid_14 --attack=True --attack_type=gaussian --attack_num=14
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_gaussian_iid_16 --attack=True --attack_type=gaussian --attack_num=16
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_gaussian_iid_18 --attack=True --attack_type=gaussian --attack_num=18

# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_pixel_iid_2 --attack=True --attack_type=pixel --attack_num=2 
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_pixel_iid_4 --attack=True --attack_type=pixel --attack_num=4
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_pixel_iid_6 --attack=True --attack_type=pixel --attack_num=6
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_pixel_iid_8 --attack=True --attack_type=pixel --attack_num=8
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_pixel_iid_10 --attack=True --attack_type=pixel --attack_num=10
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_pixel_iid_12 --attack=True --attack_type=pixel --attack_num=12
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_pixel_iid_14 --attack=True --attack_type=pixel --attack_num=14
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_pixel_iid_16 --attack=True --attack_type=pixel --attack_num=16
# python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_pixel_iid_18 --attack=True --attack_type=pixel --attack_num=18

python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_replace_iid_2 --attack=True --attack_type=replace --attack_num=2 --attack_replace_round=150
python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_replace_iid_4 --attack=True --attack_type=replace --attack_num=4 --attack_replace_round=150
python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_replace_iid_6 --attack=True --attack_type=replace --attack_num=6 --attack_replace_round=150
python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_replace_iid_8 --attack=True --attack_type=replace --attack_num=8 --attack_replace_round=150
python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_replace_iid_10 --attack=True --attack_type=replace --attack_num=10 --attack_replace_round=150
python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_replace_iid_12 --attack=True --attack_type=replace --attack_num=12 --attack_replace_round=150
python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_replace_iid_14 --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=150
python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_replace_iid_16 --attack=True --attack_type=replace --attack_num=16 --attack_replace_round=150
python FL_robust.py --round=200 --client_ep=5 --data_distributed=iid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_FedAVG_replace_iid_18 --attack=True --attack_type=replace --attack_num=18 --attack_replace_round=150