python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_01_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_01_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_01_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_02_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_02_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_02_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_03_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_03_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_03_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_04_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_04_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_04_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_05_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_05_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_05_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_06_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_06_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_06_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_07_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_07_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_07_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_08_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_08_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_08_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_09_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_09_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_09_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 

python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_1_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_1_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_1_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_2_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_2_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_2_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_3_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_3_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_3_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_4_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_4_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_4_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_5_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_5_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_5_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_6_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_6_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_6_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_7_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_7_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_7_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_8_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_8_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_8_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_9_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_9_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_9_300.pth.tar --client_id=2 --attack_server=True --attack_server_only=True 

python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_01_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_01_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_01_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_02_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_02_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_02_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_03_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_03_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_03_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_04_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_04_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_04_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_05_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_05_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_05_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_06_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_06_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_06_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_07_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_07_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_07_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_08_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_08_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_08_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_09_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_09_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_09_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 

python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_1_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_1_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_1_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_2_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_2_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_2_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_3_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_3_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_3_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_4_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_4_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_4_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_5_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_5_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_5_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_6_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_6_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_6_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_7_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_7_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_7_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_8_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_8_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_8_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 
python white_box_fmnist.py --smp_flie=iid_test_P_FedSIGN_M_FMNIST_9_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_FMNIST_9_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_FMNIST_9_300.pth.tar --client_id=3 --attack_server=True --attack_server_only=True 




