# FedAvg
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FedAVG_replace_noniid_2 --attack=True --attack_type=replace --attack_num=2 --attack_replace_round=150
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FedAVG_replace_noniid_4 --attack=True --attack_type=replace --attack_num=4 --attack_replace_round=150
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FedAVG_replace_noniid_6 --attack=True --attack_type=replace --attack_num=6 --attack_replace_round=150
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FedAVG_replace_noniid_8 --attack=True --attack_type=replace --attack_num=8 --attack_replace_round=150
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FedAVG_replace_noniid_10 --attack=True --attack_type=replace --attack_num=10 --attack_replace_round=150
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FedAVG_replace_noniid_12 --attack=True --attack_type=replace --attack_num=12 --attack_replace_round=150
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FedAVG_replace_noniid_14 --attack=True --attack_type=replace --attack_num=15 --attack_replace_round=150
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FedAVG_replace_noniid_16 --attack=True --attack_type=replace --attack_num=16 --attack_replace_round=150
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FedAVG_replace_noniid_18 --attack=True --attack_type=replace --attack_num=18 --attack_replace_round=150

# FedAVG-Krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_noniid_2 --attack=True --attack_type=replace --attack_num=2 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum 
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_noniid_4 --attack=True --attack_type=replace --attack_num=4 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_noniid_6 --attack=True --attack_type=replace --attack_num=6 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_noniid_8 --attack=True --attack_type=replace --attack_num=8 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_noniid_10 --attack=True --attack_type=replace --attack_num=10 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_noniid_12 --attack=True --attack_type=replace --attack_num=12 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_noniid_14 --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_noniid_16 --attack=True --attack_type=replace --attack_num=16 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_noniid_18 --attack=True --attack_type=replace --attack_num=18 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum

# FedSIGN
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_sign_replace_noniid_2 --attack=True --attack_type=replace --attack_num=2 
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_sign_replace_noniid_4 --attack=True --attack_type=replace --attack_num=4
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_sign_replace_noniid_6 --attack=True --attack_type=replace --attack_num=6
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_sign_replace_noniid_8 --attack=True --attack_type=replace --attack_num=8
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_sign_replace_noniid_10 --attack=True --attack_type=replace --attack_num=10
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_sign_replace_noniid_12 --attack=True --attack_type=replace --attack_num=12
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_sign_replace_noniid_14 --attack=True --attack_type=replace --attack_num=14
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_sign_replace_noniid_16 --attack=True --attack_type=replace --attack_num=16
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_sign_replace_noniid_18 --attack=True --attack_type=replace --attack_num=18

# FedSIGN-Krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_Krum_replace_noniid_2 --attack=True --attack_type=replace --attack_num=2 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum 
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_Krum_replace_noniid_4 --attack=True --attack_type=replace --attack_num=4 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_Krum_replace_noniid_6 --attack=True --attack_type=replace --attack_num=6 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_Krum_replace_noniid_8 --attack=True --attack_type=replace --attack_num=8 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_Krum_replace_noniid_10 --attack=True --attack_type=replace --attack_num=10 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_Krum_replace_noniid_12 --attack=True --attack_type=replace --attack_num=12 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_Krum_replace_noniid_14 --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_Krum_replace_noniid_16 --attack=True --attack_type=replace --attack_num=16 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_Krum_replace_noniid_18 --attack=True --attack_type=replace --attack_num=18 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum

# FedSIGN-DC
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_mipc_replace_noniid_2 --attack=True --attack_type=replace --attack_num=2 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc 
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_mipc_replace_noniid_4 --attack=True --attack_type=replace --attack_num=4 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_mipc_replace_noniid_6 --attack=True --attack_type=replace --attack_num=6 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_mipc_replace_noniid_8 --attack=True --attack_type=replace --attack_num=8 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_mipc_replace_noniid_10 --attack=True --attack_type=replace --attack_num=10 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_mipc_replace_noniid_12 --attack=True --attack_type=replace --attack_num=12 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_mipc_replace_noniid_14 --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_mipc_replace_noniid_16 --attack=True --attack_type=replace --attack_num=16 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc
python FL_robust.py --round=200 --client_ep=15 --data_distributed=noniid --update_type=direction --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.0005 --name=R_mipc_replace_noniid_18 --attack=True --attack_type=replace --attack_num=18 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc
