python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_01_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_01_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_01_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_02_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_02_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_02_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_03_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_03_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_03_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_04_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_04_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_04_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_05_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_05_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_05_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_06_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_06_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_06_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_07_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_07_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_07_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_08_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_08_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_08_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_09_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_09_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_09_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True 

python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_1_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_1_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_1_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_2_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_2_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_2_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_3_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_3_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_3_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_4_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_4_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_4_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_5_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_5_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_5_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_6_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_6_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_6_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_7_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_7_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_7_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True  
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_8_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_8_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_8_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_9_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_9_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_9_300.pth.tar --client_id=0 --attack_server=True --attack_server_only=True 

python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_01_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_01_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_01_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_02_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_02_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_02_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_03_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_03_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_03_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_04_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_04_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_04_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_05_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_05_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_05_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_06_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_06_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_06_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_07_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_07_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_07_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_08_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_08_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_08_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_09_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_09_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_09_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True 

python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_1_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_1_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_1_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_2_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_2_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_2_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_3_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_3_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_3_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_4_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_4_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_4_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_5_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_5_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_5_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_6_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_6_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_6_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_7_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_7_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_7_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True  
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_8_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_8_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_8_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True 
python white_box_mnist.py --smp_flie=iid_test_P_FedSIGN_M_MNIST_9_client_samp_idxs.pkl --client_model_file=iid_test_P_FedSIGN_M_MNIST_9_client3_round300.pth.tar --server_model_file=iid_test_P_FedSIGN_M_MNIST_9_300.pth.tar --client_id=1 --attack_server=True --attack_server_only=True 


