python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_labelflip_noniid_2 --attack=True --attack_type=label --attack_num=2 --robust_agg=True --robust_agg_type=krum 
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_labelflip_noniid_4 --attack=True --attack_type=label --attack_num=4 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_labelflip_noniid_6 --attack=True --attack_type=label --attack_num=6 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_labelflip_noniid_8 --attack=True --attack_type=label --attack_num=8 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_labelflip_noniid_10 --attack=True --attack_type=label --attack_num=10 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_labelflip_noniid_12 --attack=True --attack_type=label --attack_num=12 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_labelflip_noniid_14 --attack=True --attack_type=label --attack_num=14 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_labelflip_noniid_16 --attack=True --attack_type=label --attack_num=16 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_labelflip_noniid_18 --attack=True --attack_type=label --attack_num=18 --robust_agg=True --robust_agg_type=krum

python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_gaussian_noniid_2 --attack=True --attack_type=gaussian --attack_num=2 --robust_agg=True --robust_agg_type=krum 
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_gaussian_noniid_4 --attack=True --attack_type=gaussian --attack_num=4 --robust_agg=True --robust_agg_type=krum 
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_gaussian_noniid_6 --attack=True --attack_type=gaussian --attack_num=6 --robust_agg=True --robust_agg_type=krum 
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_gaussian_noniid_8 --attack=True --attack_type=gaussian --attack_num=8 --robust_agg=True --robust_agg_type=krum 
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_gaussian_noniid_10 --attack=True --attack_type=gaussian --attack_num=10 --robust_agg=True --robust_agg_type=krum 
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_gaussian_noniid_12 --attack=True --attack_type=gaussian --attack_num=12 --robust_agg=True --robust_agg_type=krum 
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_gaussian_noniid_14 --attack=True --attack_type=gaussian --attack_num=14 --robust_agg=True --robust_agg_type=krum 
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_gaussian_noniid_16 --attack=True --attack_type=gaussian --attack_num=16 --robust_agg=True --robust_agg_type=krum 
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_gaussian_noniid_18 --attack=True --attack_type=gaussian --attack_num=18 --robust_agg=True --robust_agg_type=krum 

python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_replace_noniid_2 --attack=True --attack_type=replace --attack_num=2 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_replace_noniid_4 --attack=True --attack_type=replace --attack_num=4 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_replace_noniid_6 --attack=True --attack_type=replace --attack_num=6 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_replace_noniid_8 --attack=True --attack_type=replace --attack_num=8 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_replace_noniid_10 --attack=True --attack_type=replace --attack_num=10 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum 
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_replace_noniid_12 --attack=True --attack_type=replace --attack_num=12 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_replace_noniid_14 --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_replace_noniid_16 --attack=True --attack_type=replace --attack_num=16 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_replace_noniid_18 --attack=True --attack_type=replace --attack_num=18 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum

python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_pixel_noniid_2 --attack=True --attack_type=pixel --attack_num=2 --robust_agg=True --robust_agg_type=krum 
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_pixel_noniid_4 --attack=True --attack_type=pixel --attack_num=4 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_pixel_noniid_6 --attack=True --attack_type=pixel --attack_num=6 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_pixel_noniid_8 --attack=True --attack_type=pixel --attack_num=8 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_pixel_noniid_10 --attack=True --attack_type=pixel --attack_num=10 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_pixel_noniid_12 --attack=True --attack_type=pixel --attack_num=12 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_pixel_noniid_14 --attack=True --attack_type=pixel --attack_num=14 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_pixel_noniid_16 --attack=True --attack_type=pixel --attack_num=16 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=5 --data_distributed=noniid --update_type=weight --dataset=fmnist --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_FMNIST_Krumavg_pixel_noniid_18 --attack=True --attack_type=pixel --attack_num=18 --robust_agg=True --robust_agg_type=krum