# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_labelflip_iid_2 --attack=True --attack_type=label --attack_num=2 --robust_agg=True --robust_agg_type=krum 
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_labelflip_iid_4 --attack=True --attack_type=label --attack_num=4 --robust_agg=True --robust_agg_type=krum
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_labelflip_iid_6 --attack=True --attack_type=label --attack_num=6 --robust_agg=True --robust_agg_type=krum
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_labelflip_iid_8 --attack=True --attack_type=label --attack_num=8 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_labelflip_iid_10 --attack=True --attack_type=label --attack_num=10 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_labelflip_iid_12 --attack=True --attack_type=label --attack_num=12 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_labelflip_iid_14 --attack=True --attack_type=label --attack_num=14 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_labelflip_iid_16 --attack=True --attack_type=label --attack_num=16 --robust_agg=True --robust_agg_type=krum
python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_labelflip_iid_18 --attack=True --attack_type=label --attack_num=18 --robust_agg=True --robust_agg_type=krum

# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_gaussian_iid_2 --attack=True --attack_type=gaussian --attack_num=2 --robust_agg=True --robust_agg_type=krum 
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_gaussian_iid_4 --attack=True --attack_type=gaussian --attack_num=4 --robust_agg=True --robust_agg_type=krum 
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_gaussian_iid_6 --attack=True --attack_type=gaussian --attack_num=6 --robust_agg=True --robust_agg_type=krum 
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_gaussian_iid_8 --attack=True --attack_type=gaussian --attack_num=8 --robust_agg=True --robust_agg_type=krum 
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_gaussian_iid_10 --attack=True --attack_type=gaussian --attack_num=10 --robust_agg=True --robust_agg_type=krum 
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_gaussian_iid_12 --attack=True --attack_type=gaussian --attack_num=12 --robust_agg=True --robust_agg_type=krum 
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_gaussian_iid_14 --attack=True --attack_type=gaussian --attack_num=14 --robust_agg=True --robust_agg_type=krum 
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_gaussian_iid_16 --attack=True --attack_type=gaussian --attack_num=16 --robust_agg=True --robust_agg_type=krum 
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_gaussian_iid_18 --attack=True --attack_type=gaussian --attack_num=18 --robust_agg=True --robust_agg_type=krum 

# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_iid_2 --attack=True --attack_type=replace --attack_num=2 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_iid_4 --attack=True --attack_type=replace --attack_num=4 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_iid_6 --attack=True --attack_type=replace --attack_num=6 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_iid_8 --attack=True --attack_type=replace --attack_num=8 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_iid_10 --attack=True --attack_type=replace --attack_num=10 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum 
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_iid_12 --attack=True --attack_type=replace --attack_num=12 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_iid_14 --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_iid_16 --attack=True --attack_type=replace --attack_num=16 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_replace_iid_18 --attack=True --attack_type=replace --attack_num=18 --attack_replace_round=150 --robust_agg=True --robust_agg_type=krum

# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_pixel_iid_2 --attack=True --attack_type=pixel --attack_num=2 --robust_agg=True --robust_agg_type=krum 
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_pixel_iid_4 --attack=True --attack_type=pixel --attack_num=4 --robust_agg=True --robust_agg_type=krum
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_pixel_iid_6 --attack=True --attack_type=pixel --attack_num=6 --robust_agg=True --robust_agg_type=krum
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_pixel_iid_8 --attack=True --attack_type=pixel --attack_num=8 --robust_agg=True --robust_agg_type=krum
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_pixel_iid_10 --attack=True --attack_type=pixel --attack_num=10 --robust_agg=True --robust_agg_type=krum
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_pixel_iid_12 --attack=True --attack_type=pixel --attack_num=12 --robust_agg=True --robust_agg_type=krum
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_pixel_iid_14 --attack=True --attack_type=pixel --attack_num=14 --robust_agg=True --robust_agg_type=krum
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_pixel_iid_16 --attack=True --attack_type=pixel --attack_num=16 --robust_agg=True --robust_agg_type=krum
# python FL_robust.py --round=200 --client_ep=15 --data_distributed=iid --update_type=weight --dataset=cifar10 --client_bs=1024 --client_lr=0.1 --model=lanet --name=R_Krumavg_pixel_iid_18 --attack=True --attack_type=pixel --attack_num=18 --robust_agg=True --robust_agg_type=krum