# python FL-privacy.py --white_box=True --round=300 --client_ep=5 --data_distributed=iid --dataset=cifar10 --client_bs=2048 --client_lr=0.01 --num_client=4 --train_num=4 --update_type=direction --model=alexnet --name=fedSIGN --sign=True --sign_alpha=0.00001
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN --sign=True --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M --sign=True --sign_mask=True --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_N --sign=True --sign_noise=True --sign_alpha=0.0001 --white_box=True

# mask 比例试验 
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_01 --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_02 --sign=True --sign_mask=True --sign_mask_p=0.02 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_03 --sign=True --sign_mask=True --sign_mask_p=0.03 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_04 --sign=True --sign_mask=True --sign_mask_p=0.04 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_05 --sign=True --sign_mask=True --sign_mask_p=0.05 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_06 --sign=True --sign_mask=True --sign_mask_p=0.06 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_07 --sign=True --sign_mask=True --sign_mask_p=0.07 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_08 --sign=True --sign_mask=True --sign_mask_p=0.08 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_09 --sign=True --sign_mask=True --sign_mask_p=0.09 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_2 --sign=True --sign_mask=True --sign_mask_p=0.2 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_3 --sign=True --sign_mask=True --sign_mask_p=0.3 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_4 --sign=True --sign_mask=True --sign_mask_p=0.4 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_5 --sign=True --sign_mask=True --sign_mask_p=0.5 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_6 --sign=True --sign_mask=True --sign_mask_p=0.6 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_7 --sign=True --sign_mask=True --sign_mask_p=0.7 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_8 --sign=True --sign_mask=True --sign_mask_p=0.8 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=cifar10 --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_9 --sign=True --sign_mask=True --sign_mask_p=0.9 --sign_alpha=0.0001 --white_box=True

# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=fmnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_FMNIST_1 --sign=True --sign_mask=True --sign_mask_p=0.1 --sign_alpha=0.0001 --white_box=True
python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_MNIST_1 --sign=True --sign_mask=True --sign_mask_p=0.1 --sign_alpha=0.0001 --white_box=True

# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_MNIST_01 --sign=True --sign_mask=True --sign_mask_p=0.01 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_MNIST_02 --sign=True --sign_mask=True --sign_mask_p=0.02 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_MNIST_03 --sign=True --sign_mask=True --sign_mask_p=0.03 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_MNIST_04 --sign=True --sign_mask=True --sign_mask_p=0.04 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_MNIST_05 --sign=True --sign_mask=True --sign_mask_p=0.05 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_MNIST_07 --sign=True --sign_mask=True --sign_mask_p=0.07 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_MNIST_08 --sign=True --sign_mask=True --sign_mask_p=0.08 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_MNIST_09 --sign=True --sign_mask=True --sign_mask_p=0.09 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_MNIST_2 --sign=True --sign_mask=True --sign_mask_p=0.2 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_MNIST_3 --sign=True --sign_mask=True --sign_mask_p=0.3 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_MNIST_4 --sign=True --sign_mask=True --sign_mask_p=0.4 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_MNIST_5 --sign=True --sign_mask=True --sign_mask_p=0.5 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_MNIST_6 --sign=True --sign_mask=True --sign_mask_p=0.6 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_MNIST_7 --sign=True --sign_mask=True --sign_mask_p=0.7 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_MNIST_8 --sign=True --sign_mask=True --sign_mask_p=0.8 --sign_alpha=0.0001 --white_box=True
# python FL-privacy.py --round=300 --client_ep=2 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --model=alexnet --num_client=4 --train_num=4 --name=test_P_FedSIGN_M_MNIST_9 --sign=True --sign_mask=True --sign_mask_p=0.9 --sign_alpha=0.0001 --white_box=True
