# python FL_robust.py --round=300 --client_ep=5 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.001 --name=V_MNIST_mipc_labelflip_iid_14 --attack=True --attack_type=label --attack_num=14 --robust_agg=True --robust_agg_type=mipc --save_mipc=True 
# python FL_robust.py --round=300 --client_ep=5 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.001 --name=V_MNIST_mipc_gaussian_iid_14 --attack=True --attack_type=gaussian --attack_num=14 --robust_agg=True --robust_agg_type=mipc --save_mipc=True
# python FL_robust.py --round=300 --client_ep=5 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.001 --name=V_MNIST_mipc_replace_iid_14 --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc --save_mipc=True
# python FL_robust.py --round=300 --client_ep=5 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.001 --name=V_MNIST_mipc_pixel_iid_14 --attack=True --attack_type=pixel --attack_num=14 --robust_agg=True --robust_agg_type=mipc --save_mipc=True

# python FL_robust.py --round=300 --client_ep=5 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.001 --name=V_MNIST_mipc_labelflip_noniid_14 --attack=True --attack_type=label --attack_num=14 --robust_agg=True --robust_agg_type=mipc --save_mipc=True 
# python FL_robust.py --round=300 --client_ep=5 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.001 --name=V_MNIST_mipc_gaussian_noniid_14 --attack=True --attack_type=gaussian --attack_num=14 --robust_agg=True --robust_agg_type=mipc --save_mipc=True
# python FL_robust.py --round=300 --client_ep=5 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.001 --name=V_MNIST_mipc_replace_noniid_14 --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc --save_mipc=True 
# python FL_robust.py --round=300 --client_ep=5 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.001 --name=V_MNIST_mipc_pixel_noniid_14 --attack=True --attack_type=pixel --attack_num=14 --robust_agg=True --robust_agg_type=mipc --save_mipc=True

python FL_robust.py --round=300 --client_ep=5 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.001 --name=V_MNIST_mipc_l2_labelflip_iid_14 --attack=True --attack_type=label --attack_num=14 --robust_agg=True --robust_agg_type=mipc --save_mipc=True --ad_dist=l2
python FL_robust.py --round=300 --client_ep=5 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.001 --name=V_MNIST_mipc_l2_gaussian_iid_14 --attack=True --attack_type=gaussian --attack_num=14 --robust_agg=True --robust_agg_type=mipc --save_mipc=True --ad_dist=l2
python FL_robust.py --round=300 --client_ep=5 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.001 --name=V_MNIST_mipc_l2_replace_iid_14 --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc --save_mipc=True --ad_dist=l2
python FL_robust.py --round=300 --client_ep=5 --data_distributed=iid --update_type=direction --dataset=mnist --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.001 --name=V_MNIST_mipc_l2_pixel_iid_14 --attack=True --attack_type=pixel --attack_num=14 --robust_agg=True --robust_agg_type=mipc --save_mipc=True --ad_dist=l2

python FL_robust.py --round=300 --client_ep=5 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.001 --name=V_MNIST_mipc_l2_labelflip_noniid_14 --attack=True --attack_type=label --attack_num=14 --robust_agg=True --robust_agg_type=mipc --save_mipc=True --ad_dist=l2
python FL_robust.py --round=300 --client_ep=5 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.001 --name=V_MNIST_mipc_l2_gaussian_noniid_14 --attack=True --attack_type=gaussian --attack_num=14 --robust_agg=True --robust_agg_type=mipc --save_mipc=True --ad_dist=l2
python FL_robust.py --round=300 --client_ep=5 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.001 --name=V_MNIST_mipc_l2_replace_noniid_14 --attack=True --attack_type=replace --attack_num=14 --attack_replace_round=150 --robust_agg=True --robust_agg_type=mipc --save_mipc=True --ad_dist=l2
python FL_robust.py --round=300 --client_ep=5 --data_distributed=noniid --update_type=direction --dataset=mnist --client_bs=1024 --client_lr=0.1 --model=lanet --sign=True --sign_alpha=0.001 --name=V_MNIST_mipc_l2_pixel_noniid_14 --attack=True --attack_type=pixel --attack_num=14 --robust_agg=True --robust_agg_type=mipc --save_mipc=True --ad_dist=l2
